<?php

declare(strict_types=1);

namespace App\Policies;

use App\Models\HealthReport;
use App\Models\Patient;
use App\Models\User;

final class HealthReportPolicy
{
    /**
     * Determine whether the user can view any health reports.
     */
    public function viewAny(User $user): bool
    {
        return $this->isAdmin($user)
            || $this->isDoctor($user)
            || $this->isCaregiver($user)
            || $this->isPatient($user);
    }

    /**
     * Determine whether the user can view the health report.
     */
    public function view(User $user, HealthReport $healthReport): bool
    {
        if ($this->isAdmin($user)) {
            return true;
        }

        $patient = $healthReport->patient;

        return $this->canAccessPatient($user, $patient);
    }

    /**
     * Determine whether the user can create health reports.
     *
     * Reports should normally be generated by a service/job,
     * but this permission allows authorized staff to trigger generation.
     */
    public function create(User $user): bool
    {
        return $this->isAdmin($user)
            || $this->isDoctor($user);
    }

    /**
     * Determine whether the user can update the health report.
     *
     * Generated reports should generally be immutable.
     * Only admin and doctor can modify a report.
     */
    public function update(User $user, HealthReport $healthReport): bool
    {
        if (
            ! $this->isAdmin($user)
            && ! $this->isDoctor($user)
        ) {
            return false;
        }

        return $this->canAccessPatient(
            $user,
            $healthReport->patient,
        );
    }

    /**
     * Determine whether the user can delete the health report.
     */
    public function delete(User $user, HealthReport $healthReport): bool
    {
        if ($this->isAdmin($user)) {
            return true;
        }

        return false;
    }

    /**
     * Determine whether the user can restore the health report.
     */
    public function restore(User $user, HealthReport $healthReport): bool
    {
        return $this->isAdmin($user);
    }

    /**
     * Determine whether the user can permanently delete the health report.
     */
    public function forceDelete(User $user, HealthReport $healthReport): bool
    {
        return $this->isAdmin($user);
    }

    /**
     * Determine whether the user can access the patient's health data.
     */
    private function canAccessPatient(
        User $user,
        Patient $patient,
    ): bool {
        if ($this->isAdmin($user)) {
            return true;
        }

        // Patient can only access their own report.
        if ($this->isPatient($user)) {
            return $patient->user_id === $user->id;
        }

        // Doctor can access only assigned patients.
        if ($this->isDoctor($user)) {
            return $patient->doctors()
                ->whereKey($user->id)
                ->exists();
        }

        // Caregiver can access only assigned patients.
        if ($this->isCaregiver($user)) {
            return $patient->caregivers()
                ->whereKey($user->id)
                ->exists();
        }

        return false;
    }

    private function isAdmin(User $user): bool
    {
        return $user->role?->value === 'admin';
    }

    private function isDoctor(User $user): bool
    {
        return $user->role?->value === 'doctor';
    }

    private function isCaregiver(User $user): bool
    {
        return $user->role?->value === 'caregiver';
    }

    private function isPatient(User $user): bool
    {
        return $user->role?->value === 'patient';
    }
}
